services:
  cloud-torrent:
    image: ghcr.io/hekrun/cloud-torrent-downloader:latest
    pull_policy: always
    container_name: cloud-torrent
    restart: unless-stopped
    ports:
      - "3000:8080"
    environment:
      DOWNLOAD_DIR: /data/downloads
      STATE_DIR: /data/state
    volumes:
      # REPLACE the left side with the exact path on your machine where you want files to save
      - ./data:/data
